apiVersion: v1
kind: Pod
metadata:
  name: pod-hostpath
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d
  volumes:
    - name: nginx-config-volume
      hostPath:
        path: /var/lib/nginx/config